### ISSUE TITLE
crash [@ nsIMEStateManager::DispatchCompositionEvent]

### ISSUE THREAD

**Issue by tmeshkova** [tmeshkova/mozilla-central#2]
got this on <code>data:text/html,<body><input><input></body></code>, 
when tried to type after page reload:

<code>
#0  0x411a87fc in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:45
#1  0x3c58e228 in nsProfileLock::FatalSignalHandler (signo=11, info=0x3ecf2dc8, context=0x3ecf2e48)

```
at /mozilla-embedlite/obj-build-n9-qt/toolkit/profile/nsProfileLock.cpp:180
```
#2  <signal handler called>
#3  0x3c792be4 in nsRefPtr<nsPresContext>::nsRefPtr (this=0x3ecf31b4, aRawPtr=0x43b91000) at ../../dist/include/nsAutoPtr.h:900
#4  0x3ca5d690 in nsEventDispatcher::Dispatch (aTarget=0x3e794b00, aPresContext=<value optimized out>, aEvent=0x3ecf3488,

```
aDOMEvent=\<value optimized out\>, aEventStatus=0x3ecf3444, aCallback=0x3ecf328c, aTargets=0x0)
at /mozilla-embedlite/content/events/src/nsEventDispatcher.cpp:553
```
#5  0x3ca70a7c in mozilla::TextComposition::DispatchEvent (this=0x3bfc5288, aEvent=0x3ecf3488, aStatus=0x3ecf3444, aCallBack=0x3ecf328c)

```
at /mozilla-embedlite/content/events/src/TextComposition.cpp:64
```
#6  0x3ca60868 in nsIMEStateManager::DispatchCompositionEvent (aEventTargetNode=0x460c7c20, aPresContext=0x40561800, aEvent=0x3ecf3488,

```
aStatus=0x3ecf3444, aCallBack=0x3ecf328c) at /mozilla-embedlite/content/events/src/nsIMEStateManager.cpp:574
```
#7  0x3c7a77f0 in PresShell::HandleEventInternal (this=0x3e70bbd0, aEvent=0x3ecf3488, aStatus=<value optimized out>)

```
at /mozilla-embedlite/layout/base/nsPresShell.cpp:6610
```
#8  0x3c7a9bd4 in PresShell::HandleEvent (this=0x3e70bbd0, aFrame=0x3e70bca8, aEvent=0x3ecf3488, aDontRetargetEvents=224,

```
aEventStatus=0x3ecf3444) at /mozilla-embedlite/layout/base/nsPresShell.cpp:6240
```
#9  0x3cbcbd4c in nsViewManager::DispatchEvent (this=<value optimized out>, aEvent=0x3ecf3488, aView=<value optimized out>,

```
aStatus=0x3ecf3444) at /mozilla-embedlite/view/src/nsViewManager.cpp:718
```
#10 0x3cbcb390 in nsView::HandleEvent (this=<value optimized out>, aEvent=0x3ecf3488, aUseAttachedEvents=<value optimized out>)

```
at /mozilla-embedlite/view/src/nsView.cpp:1010
```
#11 0x3d1c59ec in mozilla::embedlite::EmbedLitePuppetWidget::DispatchEvent (this=0x1, event=0x43b91000, aStatus=@0x3ecf3474)

```
at /mozilla-embedlite/embedding/embedlite/embedthread/EmbedLitePuppetWidget.cpp:317
```
#12 0x3d1ca0f8 in mozilla::embedlite::TabChildHelper::DispatchWidgetEvent (this=<value optimized out>, event=...)

```
at /mozilla-embedlite/embedding/embedlite/utils/TabChildHelper.cpp:736
```
#13 0x3d1c5410 in mozilla::embedlite::EmbedLiteViewThreadChild::RecvHandleTextEvent (this=0x40596c00, commit=<value optimized out>,

```
preEdit=...) at /mozilla-embedlite/embedding/embedlite/embedthread/EmbedLiteViewThreadChild.cpp:367
```
#14 0x3d38b69c in mozilla::embedlite::PEmbedLiteViewChild::OnMessageReceived (this=0x40596c00, __msg=<value optimized out>)

```
at /mozilla-embedlite/obj-build-n9-qt/ipc/ipdl/PEmbedLiteViewChild.cpp:1336
```
#15 0x3d385c90 in mozilla::embedlite::PEmbedLiteAppChild::OnMessageReceived (this=0x3ac996c0, __msg=...)

```
at /mozilla-embedlite/obj-build-n9-qt/ipc/ipdl/PEmbedLiteAppChild.cpp:373
```
#16 0x3d28cad0 in mozilla::ipc::AsyncChannel::OnDispatchMessage (this=0x3ac996c8, msg=...)

```
at /mozilla-embedlite/ipc/glue/AsyncChannel.cpp:473
```
#17 0x3d295ba8 in mozilla::ipc::RPCChannel::OnMaybeDequeueOne (this=0x3ac996c8)

```
at /mozilla-embedlite/ipc/glue/RPCChannel.cpp:402
```
#18 0x3d293274 in DispatchToMethod<mozilla::ipc::RPCChannel, bool (mozilla::ipc::RPCChannel::*)()> (obj=<value optimized out>, method=

```
(bool (mozilla::ipc::RPCChannel::*)(mozilla::ipc::RPCChannel *)) 0x3d295a5c \<mozilla::ipc::RPCChannel::OnMaybeDequeueOne()\>, 
arg=\<value optimized out\>) at /mozilla-embedlite/ipc/chromium/src/base/tuple.h:383
```
#19 0x3d2928a8 in mozilla::ipc::RPCChannel::RefCountedTask::Run (this=<value optimized out>)

```
at ../../dist/include/mozilla/ipc/RPCChannel.h:425
```
#20 0x3d535f38 in MessageLoop::RunTask (this=0x3e7931a0, task=0x43b91000)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:333
```
#21 0x3d538764 in MessageLoop::DeferOrRunPendingTask (this=0x43b91000, pending_task=...)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:341
```
#22 0x3d538940 in MessageLoop::DoWork (this=0x3e7931a0) at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:441
#23 0x3d2919b8 in mozilla::ipc::DoWorkRunnable::Run (this=<value optimized out>)

```
at /mozilla-embedlite/ipc/glue/MessagePump.cpp:42
```
#24 0x3d503d80 in nsThread::ProcessNextEvent (this=0x3bfccc40, mayWait=<value optimized out>, result=0x3ecf38c7)

```
at /mozilla-embedlite/xpcom/threads/nsThread.cpp:627
```
#25 0x3d4c7848 in NS_ProcessPendingEvents_P (thread=0x3bfccc40, timeout=20)

```
at /mozilla-embedlite/obj-build-n9-qt/xpcom/build/nsThreadUtils.cpp:188
```
#26 0x3d1a3c1c in nsBaseAppShell::NativeEventCallback (this=0x4055ace8)

```
at /mozilla-embedlite/widget/xpwidgets/nsBaseAppShell.cpp:97
```
#27 0x3d18e7bc in nsAppShell::event (this=0x43b91000, e=<value optimized out>)

```
at /mozilla-embedlite/widget/qt/nsAppShell.cpp:90
```
#28 0x41f05f04 in QVolatileImageData::QVolatileImageData (this=0x4055ace0) at image/qvolatileimagedata.cpp:50
#29 0x41f100e8 in QPngHandlerPrivate::readImageFormat (this=0x405576d0) at image/qpnghandler.cpp:557
#30 0x4176cfa0 in QString (this=0x3bdfd8e0) at ../../include/QtCore/../../src/corelib/tools/qstring.h:882
#31 QXmlStreamStringRef (this=0x3bdfd8e0) at ../../include/QtCore/../../src/corelib/xml/qxmlstream.h:122
#32 QXmlStreamReaderPrivate::resolveTag (this=0x3bdfd8e0) at xml/qxmlstream.cpp:1659
#33 0x417714f8 in QXmlStreamReaderPrivate::parse (this=0x3ecf3be7) at xml/qxmlstream_p.h:1848
#34 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4
#35 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4

Backtrace stopped: previous frame identical to this frame (corrupt stack?)
</code>

**Comment by tmeshkova** [comment]
fixed in 2cbda160f29b2e12dfccb8b8c21acde104ac9132
