### ISSUE TITLE
crash [@ EmbedLiteViewThreadParent::RecvSetInputContext]

### ISSUE THREAD

**Issue by tmeshkova** [tmeshkova/mozilla-central#3]
caught this on <code>data:text/html,<body><input><input></body></code> page, 
on close
<code>
#0  0x411a87fc in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:45
#1  0x3c58e728 in nsProfileLock::FatalSignalHandler (signo=11, info=0xae8ca658, context=0xae8ca6d8)

```
at /mozilla-embedlite/obj-build-n9-qt/toolkit/profile/nsProfileLock.cpp:180
```
#2  <signal handler called>
#3  mozilla::embedlite::EmbedLiteViewThreadParent::RecvSetInputContext (this=0x409c67c0, aIMEEnabled=@0xae8caca8,

```
aIMEOpen=\<value optimized out\>, aType=..., aInputmode=..., aActionHint=..., aCause=@0xae8caca0, aFocusChange=@0xae8cabc0)
at /mozilla-embedlite/embedding/embedlite/embedthread/EmbedLiteViewThreadParent.cpp:779
```
#4  0x3d3197c8 in mozilla::embedlite::PEmbedLiteViewParent::OnMessageReceived (this=0x409c67c0, __msg=<value optimized out>)

```
at /mozilla-embedlite/obj-build-n9-qt/ipc/ipdl/PEmbedLiteViewParent.cpp:1581
```
#5  0x3d313734 in mozilla::embedlite::PEmbedLiteAppParent::OnMessageReceived (this=0x3ac08de0, __msg=...)

```
at /mozilla-embedlite/obj-build-n9-qt/ipc/ipdl/PEmbedLiteAppParent.cpp:430
```
#6  0x3d28e290 in mozilla::ipc::AsyncChannel::OnDispatchMessage (this=0x3ac08de8, msg=...)

```
at /mozilla-embedlite/ipc/glue/AsyncChannel.cpp:473
```
#7  0x3d297378 in mozilla::ipc::RPCChannel::OnMaybeDequeueOne (this=0x3ac08de8)

```
at /mozilla-embedlite/ipc/glue/RPCChannel.cpp:402
```
#8  0x3d294a44 in DispatchToMethod<mozilla::ipc::RPCChannel, bool (mozilla::ipc::RPCChannel::*)()> (obj=<value optimized out>, method=

```
(bool (mozilla::ipc::RPCChannel::*)(mozilla::ipc::RPCChannel *)) 0x3d29722c \<mozilla::ipc::RPCChannel::OnMaybeDequeueOne()\>, 
arg=\<value optimized out\>) at /mozilla-embedlite/ipc/chromium/src/base/tuple.h:383
```
#9  0x3d294078 in mozilla::ipc::RPCChannel::RefCountedTask::Run (this=<value optimized out>)

```
at ../../dist/include/mozilla/ipc/RPCChannel.h:425
```
#10 0x3d538280 in MessageLoop::RunTask (this=0x3b860c80, task=0xae8ca9a0)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:333
```
#11 0x3d53aaac in MessageLoop::DeferOrRunPendingTask (this=0x0, pending_task=...)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:341
```
#12 0x3d53ac88 in MessageLoop::DoWork (this=0x3b860c80) at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:441
#13 0x3d55e304 in base::MessagePumpForUI::HandleDispatch (this=0x3ac0ddf0)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_pump_qt.cc:159
```
#14 0x3d55e398 in base::MessagePumpQt::event (this=0x0, e=<value optimized out>)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_pump_qt.cc:61
```
#15 0x41f05f04 in QVolatileImageData::QVolatileImageData (this=0x3ac0de08) at image/qvolatileimagedata.cpp:50
#16 0x41f100e8 in QPngHandlerPrivate::readImageFormat (this=0x4094a830) at image/qpnghandler.cpp:557
#17 0x4176cfa0 in QString (this=0x3ac0b220) at ../../include/QtCore/../../src/corelib/tools/qstring.h:882
#18 QXmlStreamStringRef (this=0x3ac0b220) at ../../include/QtCore/../../src/corelib/xml/qxmlstream.h:122
#19 QXmlStreamReaderPrivate::resolveTag (this=0x3ac0b220) at xml/qxmlstream.cpp:1659
#20 0x417714f8 in QXmlStreamReaderPrivate::parse (this=0xae8cb0d7) at xml/qxmlstream_p.h:1848
#21 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4
#22 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4

Backtrace stopped: previous frame identical to this frame (corrupt stack?)
</code>

**Comment by tmeshkova** [comment]
fixed in fbec2d974d8adbfa00900557546ebbc0d64c8cac
