### ISSUE TITLE
crash [@ EmbedLiteCompositorParent::GetEmbedPanZoomController]

### ISSUE THREAD

**Issue by tmeshkova** [tmeshkova/mozilla-central#4]
similar to #3 crash after view has been destroyed

<code>
#0  0x411a87fc in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:45
#1  0x3c58e728 in nsProfileLock::FatalSignalHandler (signo=11, info=0xaec5f2d8, context=0xaec5f358)

```
at /mozilla-embedlite/obj-build-n9-qt/toolkit/profile/nsProfileLock.cpp:180
```
#2  <signal handler called>
#3  mozilla::embedlite::EmbedLiteView::GetImpl (this=0x0) at /mozilla-embedlite/embedding/embedlite/EmbedLiteView.cpp:72
#4  0x3d1c92dc in mozilla::embedlite::EmbedLiteCompositorParent::GetEmbedPanZoomController (this=0x40a02000)

```
at /mozilla-embedlite/embedding/embedlite/embedthread/EmbedLiteCompositorParent.cpp:161
```
#5  0x3d1c9464 in mozilla::embedlite::EmbedLiteCompositorParent::ShadowLayersUpdated (this=0x40a02000, aLayerTree=0x40a2b580,

```
aTargetConfig=..., isFirstPaint=false)
at /mozilla-embedlite/embedding/embedlite/embedthread/EmbedLiteCompositorParent.cpp:136
```
#6  0x3d5dea98 in mozilla::layers::ShadowLayersParent::RecvUpdate (this=0x40a2b580, cset=<value optimized out>,

```
targetConfig=\<value optimized out\>, isFirstPaint=\<value optimized out\>, reply=0xaec5fc24)
at /mozilla-embedlite/gfx/layers/ipc/ShadowLayersParent.cpp:470
```
#7  0x3d5deb34 in mozilla::layers::ShadowLayersParent::RecvUpdateNoSwap (this=0x40a2b580, cset=..., targetConfig=...,

```
isFirstPaint=@0xaec5fca4) at /mozilla-embedlite/gfx/layers/ipc/ShadowLayersParent.cpp:154
```
#8  0x3d2f5b1c in mozilla::layers::PLayersParent::OnMessageReceived (this=0x40a2b580, __msg=<value optimized out>)

```
at /mozilla-embedlite/obj-build-n9-qt/ipc/ipdl/PLayersParent.cpp:355
```
#9  0x3d2eaa7c in mozilla::layers::PCompositorParent::OnMessageReceived (this=0x40a02000, __msg=...)

```
at /mozilla-embedlite/obj-build-n9-qt/ipc/ipdl/PCompositorParent.cpp:344
```
#10 0x3d28e2b8 in mozilla::ipc::AsyncChannel::OnDispatchMessage (this=0x40a02008, msg=...)

```
at /mozilla-embedlite/ipc/glue/AsyncChannel.cpp:473
```
#11 0x3d2973a0 in mozilla::ipc::RPCChannel::OnMaybeDequeueOne (this=0x40a02008)

```
at /mozilla-embedlite/ipc/glue/RPCChannel.cpp:402
```
#12 0x3d294a6c in DispatchToMethod<mozilla::ipc::RPCChannel, bool (mozilla::ipc::RPCChannel::*)()> (obj=<value optimized out>, method=

```
(bool (mozilla::ipc::RPCChannel::*)(mozilla::ipc::RPCChannel *)) 0x3d297254 \<mozilla::ipc::RPCChannel::OnMaybeDequeueOne()\>, 
arg=\<value optimized out\>) at /mozilla-embedlite/ipc/chromium/src/base/tuple.h:383
```
#13 0x3d2940a0 in mozilla::ipc::RPCChannel::RefCountedTask::Run (this=<value optimized out>)

```
at ../../dist/include/mozilla/ipc/RPCChannel.h:425
```
#14 0x3d5382a8 in MessageLoop::RunTask (this=0x3b860d60, task=0xaec5f644)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:333
```
#15 0x3d53aad4 in MessageLoop::DeferOrRunPendingTask (this=0x0, pending_task=...)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:341
```
#16 0x3d53acb0 in MessageLoop::DoWork (this=0x3b860d60) at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:441
#17 0x3d55e32c in base::MessagePumpForUI::HandleDispatch (this=0x3ac0de20)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_pump_qt.cc:159
```
#18 0x3d55e3c0 in base::MessagePumpQt::event (this=0x0, e=<value optimized out>)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_pump_qt.cc:61
```
#19 0x41f05f04 in QVolatileImageData::QVolatileImageData (this=0x3ac0de38) at image/qvolatileimagedata.cpp:50

---Type <return> to continue, or q <return> to quit---
#20 0x41f100e8 in QPngHandlerPrivate::readImageFormat (this=0x409ee820) at image/qpnghandler.cpp:557
#21 0x4176cfa0 in QString (this=0x3ac0b220) at ../../include/QtCore/../../src/corelib/tools/qstring.h:882
#22 QXmlStreamStringRef (this=0x3ac0b220) at ../../include/QtCore/../../src/corelib/xml/qxmlstream.h:122
#23 QXmlStreamReaderPrivate::resolveTag (this=0x3ac0b220) at xml/qxmlstream.cpp:1659
#24 0x417714f8 in QXmlStreamReaderPrivate::parse (this=0xaec600d7) at xml/qxmlstream_p.h:1848
#25 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4
#26 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4

Backtrace stopped: previous frame identical to this frame (corrupt stack?)
</code>

**Comment by tmeshkova** [comment]
fixed in 25403f16064fee88ec8808867684224f0117edf0
